# Use Node.js as the base image
FROM node:20

# Set working directory
WORKDIR /app

# Copy package.json and install dependencies
COPY package.json package-lock.json ./
RUN npm install

# Copy the rest of the project
COPY . .

# Expose the port for the API
EXPOSE 5000

# Start the application
CMD ["npm", "start"]
