name: Online Voting System CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Backend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/voting-backend:latest ./server
          docker push ${{ secrets.DOCKER_USERNAME }}/voting-backend:latest

      - name: Build and Push Frontend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/voting-frontend:latest ./client
          docker push ${{ secrets.DOCKER_USERNAME }}/voting-frontend:latest

      - name: Deploy on Remote Server
        run: |
          ssh user@server "docker pull ${{ secrets.DOCKER_USERNAME }}/voting-backend:latest && docker pull ${{ secrets.DOCKER_USERNAME }}/voting-frontend:latest && docker-compose up -d"
